### ISSUE TITLE
Interface / version check

### ISSUE THREAD

**Issue by pionl** [GravityMedia/Ghostscript#16]
Hi,

thank you for the package! )

I've got a proposal for PR I would like to make, just want to check if you are OK with this:

## 1. Provide and interface for `Ghostscript`

This would allow me to test my implementation without real implementation / mocking. This is fully optional for the end user (user needs to setup his own container dependency injection). We could provide auto discovery for Laravel.

I could even provide testing implementation (called Assert / Expectation). 

## 2. Do not check version in construct

While I'm in tests I cant use dependency injection in constructor due the fact that `gs` script is used to check version. Currently I'm injection the instance in my "implementation" to prevent my dependency injection tests failing.

I think it would be great to check version on first usage of a method `createPdfDevice,createNoDisplayDevice,createPdfInfoDevice,createInkcovDevice`

What do you think?

Thank you,

**Comment by schroedan** [comment]
Hello @pionl,

thanks for asking.

## 1. Interface
That would be perfectly fine for me.

## 2. Version check
I would also move the version check that currently happens in the constructor to the device factory methods.

Feel free to prepare a pull request for this if you like.

Thanks a lot.

**Comment by pionl** [comment]
Hi @schroedan, great, thank you, I will look into it this week. Have a great day!
