### ISSUE TITLE
Missing glyph CID=0, glyph=2713 in the font HiddenHorzOCR

### ISSUE THREAD

**Issue by taufik-acclime** [GravityMedia/Ghostscript#24]
I got this specific PDF upload by user resulting this error.

GPL Ghostscript 9.50: Missing glyph CID=0, glyph=2713 in the font HiddenHorzOCR . The output PDF may fail with some viewers.\n

**Comment by schroedan** [comment]
This is an error message from the Ghostscript binary. It can be assumed that the PDF contains an error that Ghostscript does not tolerate. However, it is not an error originating from this package. The issue is therefore closed.
