### ISSUE TITLE
No support for Symfony 3.4

### ISSUE THREAD

**Issue by BreiteSeite** [GravityMedia/Ghostscript#4]
Symfony 3.4 is still supported until Nov. 2021. https://symfony.com/roadmap/3.4

We would like to use this nice library but #2 forces the user of this library also to use symfony 4.1 which currently is not in use here as we rely on LTS versions.

Would it be okay (in the sense of would you accept a pull request) to have the requirement for `symfony/process` to something like `^3.4|^4.1`?

Thanks.

**Comment by schroedan** [comment]
Hi @BreiteSeite 

This would be definitely okay. Just send me the PR.

Regards.
